### ISSUE TITLE
[ISSUER FLOW] error "could not access ETO files data" thrown just after registration 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2761]
**DESCRIPTION**

Just after registration, the issuer gets this error saying he should check if his email/KYC is done.
This is wrong of course, as at this point the user did not have a chance to process verification yet. 

**ENVIRONMENTS**
the test happened on stage, but I guess it's everywhere now 

**STEPS TO REPRODUCE**
1. You can try it even on .io, simply use any metamask account that is not a fixture
2. /eto-landing register/login with metamask
3. This error will popup automatically the moment the dashboard loads 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/83d07f0a-64d8-46c2-a6d1-e5e778a8a45b)

**CONSOLE**
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/cf2aa505-a598-4856-bbcf-579374c65fe3)

**ACCEPTANCE CRITERIA**
- [ ] a completely new issuer doesn't have any error popups just after registering 
- [ ] the given error is not showed also when the user logged out & in without adding email or doing KYC before

**Comment by rudolfix** [comment]
you cannot ask backend for ETO data before e-mail and KYC is done
```
debug: "Exception type#<class 'platform_common.apis.decorators.NoConfirmedEmailException'>#Traceback (most recent call last):↵  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request↵    rv = self.dispatch_request()↵  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request↵    return self.view_functions[rule.endpoint](**req.view_args)↵  File "/usr/lib/python3.6/site-packages/flask_injector.py", line 73, in wrapper↵    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)↵  File "/usr/lib/python3.6/site-packages/injector/__init__.py", line 784, in call_with_injection↵    return callable(*full_args, **dependencies)↵  File "/usr/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 73, in wrapper↵    response = function(request)↵  File "/usr/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 117, in wrapper↵    response = function(request)↵  File "/usr/lib/python3.6/site-packages/connexion/decorators/response.py", line 104, in wrapper↵    response = function(request)↵  File "/usr/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 44, in wrapper↵    response = function(request)↵  File "/usr/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 207, in wrapper↵    return function(**kwargs)↵  File "/usr/lib/python3.6/site-packages/py_platform_common-0.0.4-py3.6.egg/platform_common/jwt_validation.py", line 175, in _wrap↵    return f(token, *args, **kwargs)↵  File "/usr/lib/python3.6/site-packages/py_platform_common-0.0.4-py3.6.egg/platform_common/apis/decorators.py", line 29, in _wrap↵    return f(user, *args, **kwargs)↵  File "/usr/lib/python3.6/site-packages/py_platform_common-0.0.4-py3.6.egg/platform_common/apis/decorators.py", line 47, in _wrap↵    _check_user_has_confirmed_email_address(user)↵  File "/usr/lib/python3.6/site-packages/py_platform_common-0.0.4-py3.6.egg/platform_common/apis/decorators.py", line 124, in _check_user_has_confirmed_email_address↵    raise NoConfirmedEmailException()↵platform_common.apis.decorators.NoConfirmedEmailException: User needs confirmed email address for this operation.↵"
status: 400
title: "User needs confirmed email address for this operation."
type: "platform_common.apis.decorators.NoConfirmedEmailException"
```
for https://platform.neufund.io/api/eto-listing/companies/me

**Comment by shanile** [comment]
Tested on a new address and the error message was not shown
